kuutamolabs/kld

tests/integration/cli.rs
I had issues seeing the actual error or the data it could not parse.
=> integration tests: result if deserialize fails

nix/modules/lightning-knd/default.nix, nix/pkgs/flake-module.nix, nix/pkgs/lightning-knd.nix, settings/src/lib.rs, src/lib.rs, src/wallet.rs, test-utils/src/lib.rs, tests/integration/api.rs
The transaction index and wallet are used by the Bitcoin Development Kit library that stores the funds used for opening channels.
=> Bitcoind transaction index and wallet

flake.lock, nix/modules/cockroachdb.nix, nix/modules/tests/Justfile
=> Fixes for cockroachdb, test helpers

nix/pkgs/lightning-knd.nix, nix/shell.nix
=> Re-add test dependencies to nix develop

nix/modules/cockroachdb.nix
=> also move certs dir for cockroachdb itself

nix/modules/cockroachdb.nix
=> nixos/cockroachdb: fix systemd unit path option

nix/modules/cockroachdb.nix
=> nixos/cockroachdb: fix clusterinit

nix/modules/cockroachdb.nix, nix/modules/lightning-knd/default.nix
=> nixos/cockroachdb: fixup database hostname

bors.toml, nix/modules/flake-module.nix
=> also rename example host

mgr/src/certs/mod.rs
=> make openssl cert check less chatty

mgr/src/main.rs, nix/modules/tests/kld-mgr.nix
=> kld-mgr: add test if certificates have correct permissions

nix/modules/tests/test-flake/db-00.toml, nix/modules/tests/test-flake/db-01.toml, nix/modules/tests/test-flake/kld-00.toml, nix/modules/toml-mapping.nix
=> fix toml mapping for bitcoindDisks

nix/modules/raid-config.nix
=> fix bitcoind mdadm assignment

nix/modules/flake-module.nix, nix/modules/toml-mapping.nix
=> only set root client cert on kld node

nix/modules/toml-mapping.nix
=> kld-mgr: fix extraHosts

nix/pkgs/flake-module.nix
=> make kld-mgr the default

mgr/src/config.rs, nix/modules/toml-mapping.nix
fixes https://github.com/kuutamolabs/lightning-knd/issues/236
=> kld-mgr: relax restrictions on what ip addresses needs to be specified

example/kld.toml, mgr/src/config.rs, nix/modules/toml-mapping.nix
=> pass log_level

nix/modules/telegraf.nix
=> Add prometheus client for telegraf service

example/kld.toml, kld/src/cli/client.rs, mgr/Cargo.lock, mgr/Cargo.toml, mgr/src/certs/lightning.rs, mgr/src/config.rs, mgr/src/main.rs, nix/modules/kld-toml-mapping.nix, nix/modules/kld/default.nix
fix https://github.com/kuutamolabs/kuutamocore/issues/930
=> Fix nix run kld-cli

mgr/src/config.rs, mgr/src/lib.rs
=> tidy up from code migration

Cargo.lock, kld/Cargo.toml, kld/src/api/invoices.rs, kld/src/bitcoind/bitcoind_client.rs, kld/src/bitcoind/mock.rs, kld/src/database/invoice.rs, kld/src/database/ldk_database.rs, kld/src/ldk/controller.rs, kld/src/ldk/event_handler.rs, kld/src/ldk/mod.rs, kld/src/wallet/bdk_wallet.rs, kld/tests/api/rest.rs, kld/tests/database/ldk_database.rs, kld/tests/mocks/mock_lightning.rs, nix/pkgs/kld.nix, test-utils/Cargo.toml
part of #341
using lightning, such that `provided_node_features` and `provided_init_features` are moved in the customized handler trait.
=> upgrade 0.0.116 lightning

kld/src/ldk/controller.rs, kld/src/ldk/event_handler.rs, kld/src/main.rs
Only start background processor after sync.
Set force announce channel preference to false
=> Process background events async.

Cargo.lock, kld/Cargo.toml, kld/src/settings/mod.rs, kld/tests/api/rest.rs, kld/tests/bitcoind.rs, kld/tests/database/main.rs, kld/tests/smoke/start.rs, test-utils/Cargo.toml, test-utils/src/bitcoin_manager.rs, test-utils/src/cockroach_manager.rs, test-utils/src/electrs_manager.rs, test-utils/src/kld_manager.rs, test-utils/src/lib.rs, test-utils/src/manager.rs, test-utils/src/ports.rs
=> Refactor test

Cargo.lock, kld/Cargo.toml, kld/tests/api/rest.rs, kld/tests/bitcoind.rs, kld/tests/database/main.rs, kld/tests/smoke/start.rs, test-utils/src/lib.rs
keep test artifacts when KEEP_TEST_ARTIFACTS_IN set
=> keep test artifacts

mgr/src/secrets.rs
fix #625 
(26 * 2 + 10) * 32
1952 bits
=> removed comment - this is sufficient entropy

example/kld.toml, mgr/src/config.rs, nix/modules/db-toml-mapping.nix, nix/modules/flake-module.nix, nix/modules/kld-toml-mapping.nix, nix/modules/monitor.nix, nix/modules/tests/kld.nix
=> add promtail for journal

mgr/src/flake.rs, mgr/src/install.rs, nix/modules/db-toml-mapping.nix, nix/modules/hardware.nix, nix/modules/kld-toml-mapping.nix, nix/modules/tests/test-flake/db-00.toml, nix/modules/tests/test-flake/db-01.toml, nix/modules/tests/test-flake/kld-00.toml
Reverts kuutamolabs/lightning-knd#687
=> Revert "Default no root access"

mgr/src/config.rs
=> Raise error if monitor setting is incomplete

Cargo.lock, kld/Cargo.toml, kld/src/key_generator.rs
=> use same bip39 with bdk

tui/Cargo.lock
collections of #989, #991 and #992
=> upgrade dependency of tui
